# Generated by Django 4.0.3 on 2022-04-06 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('note_mistake', models.TextField(max_length=1000, null=True, verbose_name='Замечание')),
                ('name_firm', models.CharField(max_length=50, null=True, verbose_name='Название фирмы')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('contact_details', models.CharField(max_length=100, null=True, verbose_name='Контактные данные')),
                ('full_cost', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Полная стоимость')),
                ('paid', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Оплачено')),
                ('note', models.TextField(max_length=1000, null=True, verbose_name='Примечание')),
                ('fabric', models.CharField(max_length=10, null=True, verbose_name='Производство')),
                ('documentation', models.CharField(max_length=200, null=True, verbose_name='Информ. по документам')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='TypeOfApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('text_number', models.CharField(max_length=20, verbose_name='Порядковый номер')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('note', models.TextField(max_length=250, verbose_name='Примечание')),
                ('date', models.DateField(null=True, verbose_name='Сроки')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Содержимое заявки',
                'verbose_name_plural': 'Содержимое заявок',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.typeofapp', verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_accountant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_manager',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Коммерсант'),
        ),
    ]
