# Generated by Django 3.2 on 2021-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Содержимое заявки', 'verbose_name_plural': 'Содержимое заявок'},
        ),
        migrations.AlterField(
            model_name='typeofapp',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип заявки'),
        ),
    ]
