# Generated by Django 3.2 on 2021-08-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210802_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Заявка'),
        ),
    ]
