# Generated by Django 3.2 on 2021-08-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210802_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.application', verbose_name='Заявка'),
        ),
    ]
