# Generated by Django 3.2 on 2021-08-02 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_alter_content_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_details',
            field=models.CharField(max_length=100, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Полная стоимость'),
        ),
        migrations.AddField(
            model_name='application',
            name='name_firm',
            field=models.CharField(max_length=50, null=True, verbose_name='Название фирмы'),
        ),
        migrations.AddField(
            model_name='application',
            name='paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_accountant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountant', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Коммерсант'),
        ),
    ]
