# Generated by Django 3.2 on 2021-08-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20210802_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
