# Generated by Django 3.2 on 2021-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='note_mistake',
            field=models.TextField(max_length=250, null=True, verbose_name='Замечание'),
        ),
    ]
