# Generated by Django 3.2 on 2021-08-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_content_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='date',
            new_name='limitation',
        ),
    ]
