# Generated by Django 3.2 on 2021-08-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_rename_date_content_limitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='limitation',
        ),
    ]
