# Generated by Django 3.2 on 2021-08-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_content_limitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='limitation',
        ),
    ]
