# Generated by Django 3.2 on 2021-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_remove_content_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateField(null=True, verbose_name='Сроки'),
        ),
    ]
