# Generated by Django 3.2 on 2021-08-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Заявка'),
        ),
    ]
