# Generated by Django 3.2 on 2021-08-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.status', verbose_name='Статус'),
        ),
    ]
