# Generated by Django 3.2 on 2021-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(max_length=1000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='note_mistake',
            field=models.TextField(max_length=1000, null=True, verbose_name='Замечание'),
        ),
    ]
