# Generated by Django 3.2 on 2021-08-16 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0022_application_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_manager',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Коммерсант'),
        ),
    ]
