# Generated by Django 3.2 on 2021-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_application_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documentation',
            field=models.CharField(max_length=200, null=True, verbose_name='Информ. по документам'),
        ),
        migrations.AddField(
            model_name='application',
            name='fabric',
            field=models.CharField(max_length=10, null=True, verbose_name='Производство'),
        ),
    ]
