# Generated by Django 3.2.7 on 2021-09-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, verbose_name='Наименование')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Стоимость')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dtc', models.CharField(max_length=50, verbose_name='ОТК')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('fine_date', models.DateField(verbose_name='Дата штрафа')),
                ('note', models.TextField(max_length=500, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('degree', models.IntegerField(default=3, verbose_name='Разряд')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.department', verbose_name='Участок')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.JSONField(verbose_name='Числа')),
                ('sum_clocks', models.IntegerField(default=0, verbose_name='Сумма часов')),
                ('month', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('foreman', models.CharField(max_length=50, verbose_name='Бригадир')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табеля',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Оклад')),
                ('degree', models.IntegerField(default=3, verbose_name='Разряд')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Коэффициент')),
                ('work_time', models.IntegerField(default=0, verbose_name='Часы за месяц')),
                ('extra_from_foreman', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Добавочные бригадира')),
                ('extra_from_director', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Добавочные начальника производства')),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Аванс')),
                ('breakfast', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Столовая')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('Note', models.TextField(max_length=500, verbose_name='Примечание')),
                ('name_director', models.CharField(max_length=50, verbose_name='Начальник производства')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.fine', verbose_name='Штраф')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Расчетный лист',
                'verbose_name_plural': 'Расчетные листы',
            },
        ),
        migrations.AddField(
            model_name='fine',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.worker', verbose_name='Работник'),
        ),
    ]
