# Generated by Django 4.0.3 on 2022-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(default='open', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-04-29', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dates',
            field=models.JSONField(null=True, verbose_name='Данные'),
        ),
    ]
