# Generated by Django 3.2.7 on 2021-10-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='fine',
        ),
    ]
