# Generated by Django 4.0.3 on 2022-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_timesheet_status_alter_timesheet_datasheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-04-30', verbose_name='Дата'),
        ),
    ]
