# Generated by Django 3.2.7 on 2021-10-05 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0003_auto_20211003_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
        ),
    ]
