# Generated by Django 3.2.7 on 2021-10-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0004_department_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='foreman',
            field=models.ForeignKey(limit_choices_to={'name': 'Бригадира'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Бригадир'),
        ),
    ]
