# Generated by Django 3.2.7 on 2021-10-05 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0007_alter_department_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='foreman',
            field=models.ForeignKey(limit_choices_to={'groups': [1]}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
        ),
    ]
