# Generated by Django 4.0.3 on 2022-05-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_coefficient_alter_timesheet_datasheet_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='count',
            field=models.IntegerField(default=168, verbose_name='Сумма часов'),
        ),
    ]
