# Generated by Django 4.0.3 on 2022-05-11 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0008_alter_coefficient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.manufacture', verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Начальник производства'),
        ),
    ]
