# Generated by Django 4.0.3 on 2022-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_department_manufacture_alter_manufacture_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coefficient',
            old_name='date',
            new_name='date_create',
        ),
    ]
