# Generated by Django 3.2.7 on 2021-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_alter_department_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='breakfast',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Столовая'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='extra_from_director',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Добавочные начальника производства'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='extra_from_foreman',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Добавочные бригадира'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Прочее'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Оклад'),
        ),
    ]
