# Generated by Django 4.0.5 on 2022-06-21 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0012_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='foreman',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-06-21', verbose_name='Дата'),
        ),
    ]
