# Generated by Django 4.0.5 on 2022-06-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_alter_department_foreman_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manufacture',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.manufacture', verbose_name='Производство'),
        ),
    ]
