# Generated by Django 3.2.7 on 2021-10-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_auto_20211005_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dates',
            field=models.JSONField(null=True, verbose_name='Числа'),
        ),
    ]
