# Generated by Django 4.0.5 on 2022-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_alter_department_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='date_create',
            field=models.DateField(verbose_name='Дата коэффициента'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-06-29', verbose_name='Дата'),
        ),
    ]
