# Generated by Django 4.0.5 on 2022-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_alter_coefficient_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='status',
            field=models.CharField(default='null', max_length=100, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-07-11', verbose_name='Дата'),
        ),
    ]
