# Generated by Django 3.2.7 on 2021-10-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0016_alter_timesheet_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='month',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-06', verbose_name='Дата'),
        ),
    ]
