# Generated by Django 3.2.8 on 2021-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_auto_20211006_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='sum_clocks',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-07', verbose_name='Дата'),
        ),
    ]
