# Generated by Django 3.2.8 on 2021-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0018_auto_20211007_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-08', verbose_name='Дата'),
        ),
    ]
