# Generated by Django 3.2.8 on 2021-10-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0022_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='worker',
        ),
    ]
