# Generated by Django 3.2.8 on 2021-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0027_alter_timesheet_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-15', verbose_name='Дата'),
        ),
    ]
