# Generated by Django 3.2.8 on 2021-10-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0034_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.department', verbose_name='Участок'),
        ),
    ]
