# Generated by Django 3.2.8 on 2021-10-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0035_timesheet_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salary.worker', verbose_name='Работник'),
        ),
    ]
