# Generated by Django 3.2.8 on 2021-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0036_alter_payroll_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-22', verbose_name='Дата'),
        ),
    ]
