# Generated by Django 3.2.8 on 2021-10-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0037_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'ordering': ['create_date'], 'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
    ]
