# Generated by Django 3.2.8 on 2021-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0038_alter_fine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
