# Generated by Django 3.2.8 on 2021-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0039_alter_fine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-10-24', verbose_name='Дата'),
        ),
    ]
