# Generated by Django 3.2.8 on 2021-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0041_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='fine_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата штрафа'),
        ),
    ]
