# Generated by Django 3.2.8 on 2021-10-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0046_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='card',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='extra_from_director',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='extra_from_foreman',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='work_time',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='worker',
        ),
        migrations.AddField(
            model_name='payroll',
            name='time_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.timesheet', verbose_name='Табель'),
        ),
    ]
