# Generated by Django 3.2.8 on 2021-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0047_auto_20211029_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-11-01', verbose_name='Дата'),
        ),
    ]
