# Generated by Django 3.2.8 on 2021-11-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0048_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.department', verbose_name='Участок'),
        ),
    ]
