# Generated by Django 3.2.8 on 2021-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0050_alter_department_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-11-02', verbose_name='Дата'),
        ),
    ]
