# Generated by Django 3.2.8 on 2021-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0056_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2021-11-11', verbose_name='Дата'),
        ),
    ]
